### PR TITLE
link Noevim.app

### PR DESCRIPTION
**Pull request by fibo**
added command to link Neovim.app

### CODE REVIEW

**Comment by fibo** [comment]
First of all, thanks for creating a Neomiv gui for Mac.
I followed instructions, but, as a Mac newbie I could not find how to start *Neovim*.

Launching `gnvim` I got an error

    Unable to find application named 'Neovim'

Then I found instructions [here](http://apple.stackexchange.com/questions/61473/set-macvim-as-default-application-after-homebrew-installation).

**Comment by robacarp** [comment]
It might be worth making the command ```brew linkapps neovim-dot-app``` just to avoid mangling where not intended.

**Comment by fibo** [comment]
@robacarp: I updated the pull request.

**Comment by rogual** [comment]
Good call, thanks.

**Pull request merged**
