### PR TITLE
Added macmeta support

### PR DESCRIPTION
**Pull request by bambu**
Added macmeta support as requested in #249 and #86. This only translates the Meta/Alt/Option key as such. It does not interpret the Command key as a Meta key. This can be turned on by calling:

```viml
call MacSetMacmeta(1)
```

### CODE REVIEW

**Comment by nrontsis** [comment]
Thanks a bunch! Works fine. 👍 

Any reason why you went with `call MacSetMacmeta(1)` instead of `set macmeta`?

**Comment by rogual** [comment]
There's no Neovim API to add new `set` commands.

**Comment by rogual** [comment]
Looks good to me @bambu. Before I merge this, can anyone think of a more descriptive name than `MacSetMacmeta`?

I'd rather go for self-explanatory over MacVim-compatible if possible. Happy to merge otherwise, but it won't be easy to change later.

**Comment by bambu** [comment]
How about `MacSetOptionAsMeta()`? That is similar to what Terminal / iterm2 call there setting.

**Comment by rogual** [comment]
I like that.

**Comment by bambu** [comment]
updated

**Comment by rogual** [comment]
Thanks!

**Pull request merged**
