### PR TITLE
When user double clicks try to visual select the word

### PR DESCRIPTION
**Pull request by bulkan**
This is me trying to mimic the behaviour of MacVim it's not quite the same just yet but its a beginning.

P.S: I am learning Obj-C as I go along so please be gentle :)

### CODE REVIEW

**Comment by rogual** [comment]
Hey, thanks a bunch for this. I don't want to send `<ESC>viw` on double-click because that will break if people remap those keys.

Vim actually has `<2-LeftMouse>`, `<3-LeftMouse>` etc., for double, triple, etc. clicks — we should really just send those (if Neovim still has them)

**Comment by bulkan** [comment]
Thanks for the feedback.

Just checked with the neovim python library and `<2-LeftMouse>`, `<3-LeftMouse>` works

```python
from neovim import attach

# Find the path to the socket using Activity Monitor find nvim process that Neovim.app starts
# Double click it and in the Open Files and Ports you can find the path
nvim = attach('socket', path='/var/folders/49/30k39lp17mz4_sdyz_0wcdb00000gn/T/nvimHoexAW/0')

nvim.input('<2-LeftMouse>')
```

I will update the PR as per your suggestion

**Comment by bulkan** [comment]
Using `<2-LeftMouse>` on double click has made NerdTree work with double clicks i.e file under cursor opens

**Comment by rogual** [comment]
Thank you! I merged these commits together and committed them as https://github.com/rogual/neovim-dot-app/commit/a0925c3c5f348f5f4465278ef5085e5a51d1aa1f.

**Comment by bulkan** [comment]
Awesome thanks :)

**Pull request closed without merging**
