### PR TITLE
Update gnvim support spaces in file path and set CWD relative to that file

### PR DESCRIPTION
**Pull request by Velrok**
Improvements:
  - given file path may contain spaces
  - sets the CWS to the directory of the given file

### CODE REVIEW

**Comment by rogual** [comment]
Hi, thanks for this.

Adding `-n` is good, I'll merge this part.

Setting CWD: I prefer Neovim to inherit the CWD from your terminal session by default. Doing otherwise might be useful sometimes, but I'd like to follow the principle of least magic on this one.

Spaces: I don't like this. The convention followed by every commandline program is for arguments to be a space-separated list of files, and for files with spaces to be quoted or backslash-escaped.

With this change, users would no longer be able to pass a list of files to gnvim.

**Comment by rogual** [comment]
Cherry-picked https://github.com/rogual/neovim-dot-app/commit/cf5ef099e648b58bd2e7bf51bfe93cc38ffe72ee

**Comment by Velrok** [comment]
Hi thanks for looking at this. Great work on the UI client BTW! :+1: 

The current master is not working even when spaces are escaped.
Example: `/usr/local/Cellar/neovim-dot-app/HEAD/bin/gnvim ~/Google\ Drive/notes/notes.md` will try to open `Drive/notes/notes.md` . Which is the reason I started to mess with this in the first place.

My fix for that was `"$@"`.

**Comment by rogual** [comment]
I've been doing some research, and I discovered I was wrong about what `"$@"` does. Your PR is the right fix — I'll merge it in.

**Comment by Velrok** [comment]
Happy to help. 

--
Waldemar Schwan

On 4 December 2015 at 16:40:10, Robin Allen (notifications@github.com) wrote:

I've been doing some research, and I discovered I was wrong about what "$@" does. Your PR is the right fix — I'll merge it in.

**Comment by rogual** [comment]
As for the CWD, rather than setting it to the dir of the given file (which I just realized would also break with several files) I'm thinking maybe the way to go is to set it to the current dir and pass Neovim the relative path to each file.

**Comment by Velrok** [comment]
:+1:

**Pull request closed without merging**
