### PR TITLE
Show modified bufffers and prompt to save when closing window with modified buffers

### PR DESCRIPTION
**Pull request by bambu**
Added support for a dialog to popup when closing and the close button to show if the current buffer is modified.

Changes:
- res/nvimrc:
    - Added autocmd/function to notify when a buffer has changed inorder
      to update documentEdited
    - Changed MacCloseTabOrWindow() to do rpcnotify instead of "q".
      "q" would fail when more than one file was open, or the document
      was edited. This way there will be a popup if buffers need saving.
    - Moved MacUpdateTitle to be with the other functions
- src/app.mm
    - Added support for closing alert when pressing Cmd-Q.
- src/input.mm
    - Set documentEdited when in insertmode.
- src/window.mm:
    - Added setting documentEdited when a buffer has changed
    - Displays nsalert when there are modified buffers requesting to
      save one or more files
    - On window closing, the Neovim.app will get all the modified
      buffers. Prompt whether one wants to save. If you want to save
      and the file does not have a title, the SavePanel comes up.

This is for issue #103

### CODE REVIEW

**Comment by rogual** [comment]
This is great stuff! I've been testing it out and it works very well. I did see one tiny issue, which is that you only get the 'modified' dot in the close button if the current buffer is modified, so if something in another tab or split is modified, a user could press the close button without a dot in it and still get the popup.

Looking at your code I'm thinking that might not be an easy fix, and if that's the case I'm happy to merge this anyway since it's so much better than what we have now. Just wanted to see if you agreed with that change and knew a way of implementing it easily first.

**Comment by bambu** [comment]
I did the modified dot that way because that is the way that MacVim/VimR do it. If you want it to just be set when ANY buffer is in a modified state, I dont think that would be too difficult. I think it should just be a little more vimscript to loop through all of the buffers and see if any of them are modified. 

Let me know what you prefer.

**Comment by rogual** [comment]
I'd rather follow Terminal.app than MacVim on this one. To me, the dot in the close button means, "hey, if you press this close button, you'll get a dialog." Also, when using tabs, each tab gets its own modified mark (`+`) already, so I think it would be good having the titlebar dot referring to the window as a whole.

**Comment by bambu** [comment]
Changed as requested.

**Comment by rogual** [comment]
Brilliant, thanks a bunch!

**Pull request merged**
